language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: F0Q6S8HeYDKFv3dD8yX+v/4+BG2tp/YMQnQrLnHm8/aomEzwT3jmazfFvMcBQfu2F3zfHA4cAmFUSOVqaHIsj4vXC/m+t9554XRZ9MRJMZ6OHLa8j0Sys5olmZihO/p+z/MsVDoFkG4QT+DJ47wKvocvwfS7jgCum1ve2JouCyPoQ5bwKYoQ0hMuANuU137liI6Ci8SJZnvl2svIDtya/U5B4H/IDL7xzqpyw58nolQJaygpZAHNBxujC9Vm7icQ5MSRN74Es/da/duTlt42kZn4iKWXNxn13IKAsXoWIsn6BIhdDyTyrtTSivCIC/jHlxunFcZkHWm8z5m0p4JgAHvrO10WJAJRGTn1Dj0kPepUzS2pKf8RGD0oJ+gALKpyvjF5DAgMygbelNyU3iC2a5pgTgrL2QmK8AwwjLNLG51dDlwKzNfcwzt3ocI8Rl4hL89kZGdCyDCUKRfVgwYbzlMd00TxFEiHYqKhiJOqmEEXXVSNSrwETsthHS1rjiHjLa4J6cG9xhlbZkNv/fK60pOU/GXwiAKMV4AilKEpZtABnvVwyYrXhqqbNs9EY+B44Qw6gkX0HzvO4lvMni1eRGoEGiAfGZZEij2GlqMbQ4+xmeDj25WeIQpHZ4JrhlEmrV8oX3m7tVtaIlVR38/XIIBebTvdYJ5qZ8VnCVzt3RU=
  - secure: HYnm264XvdNlbEavqNkw95aymMkqMaprwRvxvSz+dBYQxna4x5gmv5l98ZwihZeYaPeKobAZzaFLwJmftZqFfNu7Mk6xrKmJTW1B6pYg3P4tuq3G9OHJ1JIK18DWVevqgJ/XqmIE2fObjQ/bFSUVgxXFplM7EpE3giTXOUeL3+WrAdt+QfiZKcLSU6cwMQZ8hgx63DIozFXv0k9/hsM8Lsku4etGH7mhvf7DPs2JwJuyPB/+TJClBSuH6N0fWrBB2mTQI2mXR9HiiKlhqE9mVmMxlkbxnfS3JHUzN/kwSpiEp3cA5+Jqq+1hVZec/MIlCMb2Om3U99xkHt4M7R0ITUi9DTwGAR7ol9llRniaCCc1w30G8JG+KYApv6P6Dw39P3WsayWPwJmO3t21r1hvj2oIttbdquC+++iku9iITmzAUZ7B5y+KbByU4Lr5VSbeIhMRLTFISx7t7c70knsH/1ylQG/O4eeMRekIdXNR5fl/UgwNNC9EaPUxz+1TFLNaiIApT5d0VOBxUVmatpWNVlqtk8kPucxkNDvEOsXhKBPbwZbYL7Rr7somoqmRnF1M5pCjm+7gdkbZdAoATH1lamIxcRm+H7mhxMcsnXfIIaZo0A/PJQNNa9pJYzX1Fe7jx9C63C21ArRi8jXw44W93PbuJPFSwJgk17d/CPx1fww=
