language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: g1d+d+NaCxU8W70nO33ojLkpvcB5GHK06UXiNlpYShqEYjkmI/+mzgTXJ/XJAJ1FtoEdVF5WUuJBWsKvwZbCtHvtczQ5y5OhemHVC/5kxX/AFZsUIhUAk5aKghYaycDEN/Jyyj1HVZ2NCqwul+pR7YcGRXbvZXpGRhp049qcpLHcH0cHu9N+u4r2gFjAdth98Prmo47VGZL4zAs7eRqnNp7ZRNRhDjJfxRGbuW/oExSH2obp9JeomOfa7L6/TI4595XCGfrLaz8tqIPwGiz8ZVU6PfKqk4gtAzq4ZWooegT09GxGXyzlSbBPd8O3U8AoZaeYZXDfslgYg5r23rgDgaYm5z4wZFewyow/71YMTif6yLHTElHCfEYI4tr7oXUwL8/+j942LpCAE7ZKI3pqGcP+KnUAy/KO58m62/uzJprgGJHz6aE9kh+tvmLQxdvAx8OZEk3rGlLQMXmkJlxogvnk8rQo9R8OATul0d0GdWde1TuWXEp8GeKqwHhjZOx9Yn9q34rO8fiymm1pT4hW3AZ2tEggC/XDWkhGizSb5YGR8te7MaExMx7BG4FjNZ0il34Nn8zO6L46i8LW8h2ZiLMXja2Y/NlTUVLIBXyI2qmZuI6gVg8Dtkqa/Eo0vOSXXnnUhFESQ2f/rdcQeKmpo8t8z5+nK9Bk3RBxfjfVVUE=
  - secure: m8imHGZNsGZjpAZggr/6p1Nbfk1LJ0b8Fuvn5QVOiehSCbgUTU23LtiynCrVePVKqtlE7WIIGk6twrStiXAFvw4yFTFdUQb0fGHf+VRqSIRg3FelQ1gD2rQDt0x84EEkPkq2bPqOkIepcRwvlA2eW5tsjEDmb3phe9SxvBLbA2adSYecMVE3wWln8ezYzLBQZGM+v1HRqGskkHb+GJv6KxCNXeUJn/v0kQf+Pi05IPWfsqMo1n8kQMFxZlK/vVXVxSbcP7Zwz2mwzDu7hiztcM7x3TBDhHZc05cRqfE5O1PewuuvaZxPFc3k+k+KjJ1t8+o1orqCRmbPkrPxDCCFNMLhulKlZI6iB7CI7un9YkeInYpQA8Ku0VPeKIYCclgXtCCbHrDUNVq53oH5oLEWsc2blAPhmCkK9RT7iOeF43JiPVA7rQ2sV2fe5uavrJ4vVWWnXjC5cJI5VfkfQae6iNCu94tISylCQ8xV3runTQRvz6zmaNQikwZZ/V9dsVA20oKUitJpHvbFoR3lQFGc4fxhioKYJzaIAgm3vlaKmYgTT5WkmACVBJ551p4rTnAK58c1w1wmJcesm1NYxsJyma0JJ2T+7Cfq3WONLVKt/R5jw4VTkpuYwSKCPRM6uS1G9ZHTGGX3GeoL28vOLVZ6NqqHVVBMu2AIMnRspZv+KGM=
