language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: hFMpUtYL8MUfEinwu9tfX/jExEA6jEtv+ZrOVzrNbbaLO+ZTccFBMI93ajUz6GqPYe20DOIcQOHnRCmZ1jwFaskojwoP06jMdMUbEfLDS1iOhlFkIKkGpFlv/MLTNQDF66pLaC2yk12D6uGbS6KCWa2uuXwrHm7BfG6DoiWizt1SpbLKHxnHBlk0aZCHizaWYsFW/pxcGYMkGnMkMsWHYmtC5qdZb4DK8xbaRwPsIPoqcCufhcXE4KGKgsrwEU6tUGbrU9UkDc7kpykdPMYMcH0Q1bSByw9/R8WJNLwDgQdetDhViBP6P+77VCIZtqAC1BuS9v5htG+mixKZIt/J/nRU7WqWzIHQzQQiejC7L38b7gKOSC3iH5xLWtQ9Yu2cOs0xnTNuVHEtiNYLWVLdAxtKRYUA+cMMzqWdbLHSGRT3m6hN4ZOjDK9alnZEXAL/oXqsqzvFRLdNXND/0ZrFN6Uoo8LJak1CXjrWKHOvXCA+Zdb7nMt1c5xS7HTOv9slN1iZMQU8nXxHMEbvLW52NW8UlxNonojO6HLS80U69IV6vBWiGctqrvbFrs+o9L1dkYD1tIM7qHx41YeMsfPvD6Rw+mN0JBQUQyREkQxHUJeLh45/yizqoxaOHfvsx5Gx7gdxH9BCoYL5u00NovMW9BdIwOEISxYFDvrWZEe/rDU=
  - secure: GSD6jq/FBJsjlH6a4Vx2a8/aa47i1BPO+Q02JzO2cV0smA3gWEzm0Rl/0KkmNey5MqjrOM4ivOph7qNgCnRbcZzmkpORNcQ3jGAe0wZxhHhpalmQSTmQE4YCEmw5UUMoOFYo7QnsdK1GUCLGENFX5rX0Fe8VuZJMPrt/dJEr115kOFHrBcPhOr3wV+0jTStKYAXRzaPPFHJ2+JUC7tqPMkZqK6CKHARC6+mj4Ou1wSPxWrsx+UtXl70tvl3a2baJ3f5MpQKhBsYFCL/XOxwIIQvPBgE8Jjoa08FnDv6hICNPxWAF8rty8RlZHrQ4t4TZyWDn93MR8PWymI/rWbnxo89AWM1/HDDIgy6DKxzp1OB8lJ4CPMC/+1pP+mmslhR70foWN6keqZEDjcigdrfeTr1E8m1nNeNJcNu4PRTyWsnS2zxG1Y8dpvctFN8ivXA4JM+F+GO0aAEgFRczUvViJ3iRaXhVCPD+dxrniTNaXoPpnnnMdze+Gw5gB0fkKXO+TMSGX9+zzKq6XCHsBaGDyK2kVzJrR/WOyS5eiZ8wOwmJtuk7ZJkuq3GPWl+H4zj9IfGAKhBEDKXhABFIHVabbROVhFa0QrPao+Kyzo08IgzFCIsP3ACyQvy2Fl020V2yW/jfT+MBZQNsQyesWOAOiJhO+7/aKVB/Lv5mKvRcCl4=
