baseURL = "https://www.emmarifai.com/"
languageCode = "en-us"
title = "Emma Rifai"
theme = "resume"

[params]
    firstName = "Emma"
    lastName = "Rifai"
    address = "Iowa City, IA"
    university = "The University of Iowa"
    phone = "1-555-555-1234"
    contactNote = ""
    profileImage = "img/emma.jpg"
    email = "emma-rifai@uiowa.edu"
    description = "PhD Candidate in Religious Studies at The University of Iowa"
    favicon = "img/emma-favicon.ico"
    # what sections
    showHonorsAwards = true
    showPublications = true
    showTeaching = true
    showPresentations = true
    showResearch = true
    showEducation = true
    showService = true
    showContact = true

    [params.facebook]
        appid = "1118082925015603"

[[params.handles]]
    name = "Email"
    link = "mailto:emma-rifai@uiowa.edu"
    icon = "envelope" #optional icon attribute used for Font Awesome icons

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/emmarifai/"

[[params.handles]]
    name = "Google Scholar"
    link = "https://scholar.google.com/citations?user=zL3di_0AAAAJ&hl=en"
    icon = "graduation-cap" #optional icon attribute used for Font Awesome icons





[params.google.analytics]
    trackerID = "XX-123446-01"
